codecov:
  branch: trunk
  bot: RavenX8
  notify:
    require_ci_to_pass: yes   
                              

coverage:
  precision: 2
  round: down
  range: "70...100"
        
  status:
    project:
      default:
        target: auto
        threshold: 1
        branches: trunk

    patch:
      default:
        target: auto

    changes:
      default:
        branches: trunk

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: new
