sudo: false
language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    - cmake
    - gcc-5
    - g++-5
    - libmysqlcppconn-dev
    - libmysqlcppconn7v5 # may not need this
  
#install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

env:
  global:
    - GCC_VERSION="5"
    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release