sudo: false
language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    - cmake
    - gcc
    - g++
    - libmysqlcppconn-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

env:
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
