language: cpp

compiler:
  - gcc
  
#addons:
#  apt_packages:
#    - libboost-all-dev
    
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu/ trusty main"
  - sudo add-apt-repository -y "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.7"
  - sudo apt-get update -qq
  - git submodule update --init --recursive
  
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - sh install_dependencies.sh

before_script:
  - mkdir build
  - cd build
  - cmake ..
  

script: make

env:
  global:
    - GCC_VERSION="4.9"
    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
