language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu/ trusty main"
  - sudo apt-get update -qq
  - git submodule update --init --recursive
  
install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - sudo apt-get install -qq cmake # install the latest version of cmake
  - wget http://iweb.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.gz -O /tmp/boost-1.59.tar.gz
  - tar -xvf /tmp/boost-1.59.tar.gz
  - wget http://cdn.mysql.com//Downloads/MySQL-5.7/mysql-5.7.9.tar.gz -O /tmp/mysql-5.7.9.tar.gz
  - tar -xvf /tmp/mysql-5.7.9.tar.gz
  - wget http://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.6.tar.gz -O /tmp/mysql-connector.tar.gz
  - tar -xvf /tmp/mysql-connector.tar.gz
  - cp -r boost_1_59_0/boost 3rdParty/include/
  - cd mysql-5.7.9
  - mkdir build
  - cd build
  - cmake -DWITH_BOOST=../../boost_1_59_0 ..
  - make && make install
  - cd ../../mysql-connector-c++-1.1.6
  - mkdir build
  - cd build
  - cmake ..
  - make && make install
  - cd ../..

before_script:
  - cd build
  - cmake ..
  

script: make

env:
  global:
    - GCC_VERSION="5"
    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
