language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    - cmake
    
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
  - git submodule update --init --recursive
  
install:
  - sudo apt-get install -qq libmysqlcppconn7v5
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
  

script: make

env:
  global:
    - GCC_VERSION="5"
    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
