language: cpp
matrix:
  include:
    - compiler: gcc
      env: GCC_VERSION="4.9" BUILD_TYPE=Debug
    - compiler: gcc
      env: GCC_VERSION="4.9" BUILD_TYPE=Release
    - compiler: gcc
      env: GCC_VERSION="5" BUILD_TYPE=Debug
    - compiler: gcc
      env: GCC_VERSION="5" BUILD_TYPE=Release
    - compiler: clang
      env: LIBCXX=1 BUILD_TYPE=Debug
    - compiler: clang
      env: LIBCXX=1 BUILD_TYPE=Release
    - compiler: clang
      env: UNSUPPORTED_FOR_NOW=1 BUILD_TYPE=Debug
    - compiler: clang
      env: UNSUPPORTED_FOR_NOW=1 BUILD_TYPE=Release
  allow_failures:
    - env: LIBCXX=1 BUILD_TYPE=Debug
    - env: LIBCXX=1 BUILD_TYPE=Release
    - env: UNSUPPORTED_FOR_NOW=1 BUILD_TYPE=Debug
    - env: UNSUPPORTED_FOR_NOW=1 BUILD_TYPE=Release

before_install:
- export MAIN_PATH=$(pwd)
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu/ trusty main"
- sudo add-apt-repository -y "deb http://repo.mysql.com/apt/ubuntu/ precise mysql-5.7"
- sudo apt-get update -qq
- git submodule update --init --recursive

#get the latest version of gcc
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
- if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "clang-3.6"; fi
#- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
- export BS_FLAGS="--cxx=$CXX"

# Install libc++
- if [ -n "$LIBCXX" ]; then export BS_FLAGS="$BS_FLAGS --use-libcxx"; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
- if [ -n "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

# Otherwise attempt to install g++ 4.8 libstdc++ instead for use in clang
- if [ -z "$LIBCXX" -a "$CXX" == "clang++" ]; then sudo apt-get install -qq g++-4.9; fi

install:
- cd "$MAIN_PATH"
- sh install_dependencies.sh

before_script:
- mkdir build
- cd build
- cmake ..
script: make -j 2
notifications:
  slack:
    secure: KHU2ZMzBGGtsaWF7wylutlLPAxCEZD2/NQQbmbaEpsaWSitXnO9XOLRLsLJP6QGLOgiDHHmGcRiO7wgmbsvP79zRaChs/LLfUY2F5laXgpZdL9OI/z8zygeY1iSZSNMMr0MCYf7TilRvOqTSFpB7RcuQ65G1ZGow8h6MunU5WaSyjC7REOJcSmL3IQ08Zcf8oZgdd6EqogSW1Eubcp4IhlsiQQTLdzeAQWwkfJ8DDO1gPC8bWdJCBg9hMUub5K/UQHEOY8KmH1KTOk/FedjI8wTWD+0m8SjFJq8wUs9ieQyGikZbK6F8WmjZdG0GLRWb7POxIOQjqxi2/ZRUMTHvDr5s+0BUQmKYUwkc/oUf/Bg/eYnU/LjM7prnQU08ZPGDwoh5L/alZM4eGKez3KFb4Co3e7HSI+FN9mQFKcgjnMOJIE1kaw1V+9Uj1DJemWi6voKmApJ3s8U44FduI30fpAD0FQQw8dEfF2Iug3O093KdPy0aEySOZ44a0VYD5iB7Dc129xumwOd5EAvGXHc+3/Wf0TLsskct2IlNVv6DaKkstk0YXjz7PkhkMJEAvYYi/ANQ8h/Ixh7Xnj7bcX+boBazIM6V+U6sxysQUsvWihXpxtqs+N7Z0eiRbC7s4TAMX1hVVvoERlLRVOTCl+QsRemTgt1QXV0rMl78h8xg8lg=
