sudo: false
language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    - cmake
    - gcc-5
    - g++-5
    - libmysqlcppconn-dev
  
#install:
#  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make

env:
  global: 
    TARGET_X=x86_64-pc-linux-gnu CC_X=gcc-5 CXX_X=g++-5
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release