language: cpp

compiler:
  - gcc
  
addons:
  apt_packages:
    - libboost-all-dev
    - cmake
    
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y "deb http://mirrors.kernel.org/ubuntu/ trusty main"
  - sudo apt-get update -qq
  - git submodule update --init --recursive
  #- wget http://mirrors.kernel.org/ubuntu/pool/main/m/mysql-connector-c++/libmysqlcppconn-dev_1.1.3-5_amd64.deb
  #- sudo dpkg -i libmysqlcppconn-dev_1.1.3-5_amd64.deb
  #- wget http://mirrors.kernel.org/ubuntu/pool/main/m/mysql-connector-c++/libmysqlcppconn7_1.1.3-5_amd64.deb
  #- sudo dpkg -i libmysqlcppconn7_1.1.3-5_amd64.deb
  
install:
  - sudo apt-get install -qq libmysqlcppconn-dev
  - sudo apt-get install -qq libmysqlcppconn7
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi

before_script:
  - wget https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.6-linux-ubuntu12.04-x86-32bit.tar.gz -O /tmp/mysql-connector.tar.gz
  - tar -xvf /tmp/mysql-connector.tar.gz
  - export PATH=$PATH:$PWD/mysql-connector-c++-1.1.6/bin/
  - mkdir build
  - cd build
  - cmake ..
  

script: make

env:
  global:
    - GCC_VERSION="5"
    
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
