codecov:
  branch: trunk
  bot: RavenX8
  notify:
    require_ci_to_pass: yes   
                              

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        threshold: 1
        attachments: "sunburst, diff"
        
  status:
    project:
      default:
        target: auto
        threshold: 1
        branches: null

    patch:
      default:
        target: auto

    changes:
      default:
        branches: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: new