name: C/C++ CI

on: [push]

jobs:
  build:
    name: Linux Release Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Install Dependencies
      run: |
        sudo apt install -y libncurses5-dev libreadline-dev
        sudo pip install pyparsing
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Make
      run: |
        cd build
        cmake --build .
